version: '3.8'

services:
  postgres_sso:
    image: postgres:15
    environment:
      POSTGRES_DB: ssotest
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  sso:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_sso
      - otel-lgtm
    environment:
      CONFIG_PATH: "config/local_test.yaml"
    ports:
      - "44043:44043"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs   # Share the logs directory with host/promtail
    logging:
        driver: "loki"
        options:
          loki-url: "http://otel-lgtm:3100/loki/api/v1/push"
          loki-external-labels: "job=sso,stack=otel-lgtm"

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./config/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - ./logs:/app/logs:ro
    command:
      - -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - otel-lgtm

  otel-lgtm:
    image: grafana/otel-lgtm:latest
    ports:
     - "3000:3000"  # Grafana
     - "3100:3100"  # Loki
     - "3200:3200"  # Tempo
     - "4317:4317"  # OpenTelemetry gRPC
     - "4318:4318"  # OpenTelemetry HTTP
     - "9090:9090"  # Prometheus
    restart: unless-stopped
