version: '3.8'

services:
  postgres_sso:
    image: postgres:15
    environment:
      POSTGRES_DB: ssotest
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  sso:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_sso
    environment:
      CONFIG_PATH: "config/local_test.yaml"
    ports:
      - "44043:44043"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./config/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - ./logs:/app/logs:ro
    command:
      - -config.file=/etc/promtail/promtail-config.yaml
