name: CD

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installing Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Server build
        run: go build -o sso cmd/sso/main.go
