name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installing Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Establishing dependencies
        run: go mod tidy

      - name: Running a linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run

      - name: Running tests
        run: go test -v ./...

      - name: Server build
        run: go build -o sso cmd/sso/main.go

